import { createClient } from '@supabase/supabase-js';

export const SUPABASE_CONFIG = {
  projectName: 'Trading-Journal2026',
  projectId: 'zsabrwibbgooyapighje',
  supabaseUrl: (import.meta.env.VITE_SUPABASE_URL || 'https://zsabrwibbgooyapighje.supabase.co').trim(),
  supabaseAnonKey: (import.meta.env.VITE_SUPABASE_ANON_KEY || 'sb_publishable_SyfEecNbKN7R4AcrVYUwRQ_0_elnc1c').trim(),
  photoBucket: 'trade-photos',
};

export const supabase = createClient(
  SUPABASE_CONFIG.supabaseUrl,
  SUPABASE_CONFIG.supabaseAnonKey,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);

export async function getPhotoUrl(path: string | null | undefined): Promise<string> {
  if (!path) return '';
  // If it's already a full data url or external url
  if (path.startsWith('data:') || path.startsWith('http://') || path.startsWith('https://')) {
    return path;
  }
  try {
    const { data } = supabase.storage.from(SUPABASE_CONFIG.photoBucket).getPublicUrl(path);
    if (data?.publicUrl) return data.publicUrl;

    const { data: signedData, error } = await supabase.storage
      .from(SUPABASE_CONFIG.photoBucket)
      .createSignedUrl(path, 3600);
    if (!error && signedData?.signedUrl) {
      return signedData.signedUrl;
    }
  } catch (err) {
    console.warn('Error fetching photo URL:', err);
  }
  return '';
}

export const SUPABASE_SQL_SCHEMA = `-- Run this in your Supabase Dashboard -> SQL Editor
-- Project: Trading-Journal2026 (zsabrwibbgooyapighje)

-- 1. Create trades table
create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  date text,
  time text,
  asset text not null,
  info text,
  external_id text,
  type text,
  direction text,
  amount numeric default 0,
  stake numeric default 0,
  payout numeric default 0,
  profit_percent numeric default 0,
  income numeric default 0,
  profit numeric default 0,
  open_price numeric default 0,
  close_price numeric default 0,
  expiry text,
  open_time text not null,
  close_time text,
  result text,
  strategy text,
  strategy_note text,
  mistake_note text,
  notes text,
  photo_path text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.trades enable row level security;

-- 3. Create RLS Policies
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'trades' and policyname = 'Users can view own trades') then
    create policy "Users can view own trades" on public.trades for select using (auth.uid() = user_id);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'trades' and policyname = 'Users can insert own trades') then
    create policy "Users can insert own trades" on public.trades for insert with check (auth.uid() = user_id);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'trades' and policyname = 'Users can update own trades') then
    create policy "Users can update own trades" on public.trades for update using (auth.uid() = user_id);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'trades' and policyname = 'Users can delete own trades') then
    create policy "Users can delete own trades" on public.trades for delete using (auth.uid() = user_id);
  end if;
end $$;

-- 4. Enable Realtime on trades table
alter publication supabase_realtime add table public.trades;

-- 5. Storage Bucket for trade-photos
insert into storage.buckets (id, name, public)
values ('trade-photos', 'trade-photos', true)
on conflict (id) do update set public = true;

-- Storage policies
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'objects' and policyname = 'Allow authenticated users to upload trade photos') then
    create policy "Allow authenticated users to upload trade photos" on storage.objects
      for insert with check (bucket_id = 'trade-photos' and auth.role() = 'authenticated');
  end if;
  if not exists (select 1 from pg_policies where tablename = 'objects' and policyname = 'Allow public viewing of trade photos') then
    create policy "Allow public viewing of trade photos" on storage.objects
      for select using (bucket_id = 'trade-photos');
  end if;
  if not exists (select 1 from pg_policies where tablename = 'objects' and policyname = 'Allow authenticated users to delete photos') then
    create policy "Allow authenticated users to delete photos" on storage.objects
      for delete using (bucket_id = 'trade-photos' and auth.role() = 'authenticated');
  end if;
end $$;
`;
